### ISSUE TITLE
Error: Cannot find module 'eslint-config-meteor' 

### ISSUE THREAD

**Issue by dcsan** [iDoMeteor/eslint-config-meteor#2]
after  -g install the requirements 
i still get this error

![image](https://cloud.githubusercontent.com/assets/514002/9705864/f2ac7a6e-5487-11e5-9c3a-7ce580e933c2.png)

**Comment by iDoMeteor** [comment]
Thanks, they must have updated the rule properties.  I will make this
correction and update the package today.

**Comment by iDoMeteor** [comment]
Should be good to go, let me know if you have any further syntactical issues.
