### ISSUE TITLE
Npm package namespace for official Meteor config

### ISSUE THREAD

**Issue by dburles** [iDoMeteor/eslint-config-meteor#4]
Hey @iDoMeteor as part of https://github.com/meteor/meteor/pull/8045 we are looking at creating an official configuration (based on the guide) for use within the newly added scaffold feature. This is something that I am happy to maintain under another repo. Please let me know if that's a possibility, thanks!

**Comment by iDoMeteor** [comment]
I might be interested in participating.  I'll look into the guide recommendations and the scaffold when I get a chance, I'm not really familiar with either atm.  You can contact me directly @ Gmail/Hangouts  using the same handle.

**Comment by dburles** [comment]
Yeah no problem, as I said I'm happy to put it together I'll post a link to the repo once I've made a start

**Comment by iDoMeteor** [comment]
Have you checked my meteor-skeleton?  It's kind of out-dated, but has some
good methodologies. I'm not a big fan of the guide, it pushes too much
towards using add-ons and impractical architecture for most apps.

**Comment by dburles** [comment]
Hey @iDoMeteor I've got a configuration [underway here](https://github.com/dburles/eslint-config-meteor) with the aim that it will be the official configuration documented within the Meteor guide! It would be great if we could use the `eslint-config-meteor` namespace on npm, if not I'll have to think of another name, or potentially, it might live under the `@mdg` namespace.

**Comment by iDoMeteor** [comment]
I'll consider giving you write access or merging your changes into my repo,
have you read my config?  Taken any of my rules into consideration?

**Comment by iDoMeteor** [comment]
MDG tried to get this namespace from me before they adopted the AirBNB.

**Comment by dburles** [comment]
I don't see any reason to have to replace your existing repo if that's a concern. I did have a quick look at your configuration.
