### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by suryaiiit** [iDoMeteor/eslint-config-meteor#5]
http://eslint.org/docs/rules/space-after-keywords
http://eslint.org/docs/rules/space-return-throw-case

Those two are replaced.

I'm not sure about others, If I know I'll let you know.

Can we update the package with all the new rules??

**Comment by iDoMeteor** [comment]
Yes, I will do so in the next few days. You are welcome to submit a pull
request in the meantime.

J

And, thank you very much for bringing this to my attention.

**Comment by iDoMeteor** [comment]
These have been replaced with keyword-spacing.  I will bring the rest of the file fully up to date soon-ish :)
